sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLZSPPT8gG3LPW64
    access-key-secret: U6k1br0z8ga0IXv3nXbulGTUzy6Pd7
    bucket-name: sky-itcast
  wechat:
    appid: wx0756f68bec5028e6
    secret: 78bb028d9c180cf7b41885299999287b
  redis:
    host: 192.168.40.140
    port: 6379
    password: 123456
    database: 0